server.port=8080

spring.application.name=API-GATEWAY

spring.cloud.gateway.routes[0].id=product-service
spring.cloud.gateway.routes[0].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/products,/products/**

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

management.endpoint.gateway.enabled=true
management.endpoints.web.exposure.include=health,info,gateway
