server.port=8083

spring.application.name=STOCK-SERVICE

eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

management.endpoints.web.exposure.include=health,info

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}

app.rabbitmq.stock.exchange=${STOCK_EVENTS_EXCHANGE:stock.exchange}
app.rabbitmq.stock.request-queue=${STOCK_REQUEST_QUEUE:stock.check.request.queue}
app.rabbitmq.stock.response-queue=${STOCK_RESPONSE_QUEUE:stock.check.response.queue}
app.rabbitmq.stock.request-routing-key=${STOCK_REQUEST_ROUTING_KEY:stock.check.request}
app.rabbitmq.stock.response-routing-key=${STOCK_RESPONSE_ROUTING_KEY:stock.check.response}
